#!/bin/bash -e
set -o pipefail

# From https://stackoverflow.com/a/4774063
WORKSPACE_PATH="$( cd "$(dirname "$0")" > /dev/null 2>&1; pwd -P )"
if [[ "$WORKSPACE_PATH" = '' ]]; then
  echo ''
  exit 1
fi

python3 "$WORKSPACE_PATH"/src/aottool/aottool.py "$@"
