#!/bin/bash -eo pipefail

# From https://stackoverflow.com/a/4774063
WORKSPACE_PATH="$( cd "$(dirname "$0")" > /dev/null 2>&1; pwd -P )"
if [[ "$WORKSPACE_PATH" = '' ]]; then
  echo ''
  exit 1
fi

if [[ ! -d "$WORKSPACE_PATH"/src/treetool/node_modules ]]; then
  pushd "$WORKSPACE_PATH"/src/treetool &> /dev/null
  yarn install
  popd &> /dev/null # $WORKSPACE_PATH
fi

node "$WORKSPACE_PATH"/src/treetool "$@"
